In [10]:
import pandas as pd
import numpy as np
import kagglehub
import os
from dateutil import parser
from pytz import timezone

In [11]:
path = kagglehub.dataset_download("notlucasp/financial-news-headlines")

csv1 = os.path.join(path, 'cnbc_headlines.csv')
csv2 = os.path.join(path, 'guardian_headlines.csv')
csv3 = os.path.join(path, 'reuters_headlines.csv')

df1 = pd.read_csv(csv1)
df1

,Headlines,Time,Description
0,Jim Cramer: A better way to invest in the Covi...,"7:51 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer recommended buying..."
1,Cramer's lightning round: I would own Teradyne,"7:33 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer rings the lightnin..."
2,NaN,NaN,NaN
3,"Cramer's week ahead: Big week for earnings, ev...","7:25 PM ET Fri, 17 July 2020","""We'll pay more for the earnings of the non-Co..."
4,IQ Capital CEO Keith Bliss says tech and healt...,"4:24 PM ET Fri, 17 July 2020","Keith Bliss, IQ Capital CEO, joins ""Closing Be..."
...,...,...,...
3075,Markets lack Christmas cheer,"10:15 AM ET Tue, 26 Dec 2017","According to Kensho, here's how markets have f..."
3076,Cramer Remix: The biggest mistake you can make...,"11:12 AM ET Thu, 20 Sept 2018",Jim Cramer revealed his top rule when it comes...
3077,Cramer says owning too many stocks and too lit...,"7:07 PM ET Fri, 22 Dec 2017",Jim Cramer broke down why owning fewer stocks ...
3078,Cramer: I helped investors through the 2010 fl...,"7:07 PM ET Fri, 22 Dec 2017","Jim Cramer built on his ""nobody ever made a di..."
3079,Cramer: Never buy a stock all at once — you'll...,"6:52 PM ET Fri, 22 Dec 2017",Jim Cramer doubled down on his key investing r...

In [12]:
df2 = pd.read_csv(csv2)
df2

            Time                                          Headlines
0      18-Jul-20   Johnson is asking Santa for a Christmas recovery
1      18-Jul-20  ‘I now fear the worst’: four grim tales of wor...
2      18-Jul-20  Five key areas Sunak must tackle to serve up e...
3      18-Jul-20  Covid-19 leaves firms ‘fatally ill-prepared’ f...
4      18-Jul-20  The Week in Patriarchy  \n\n\n  Bacardi's 'lad...
...          ...                                                ...
17795  17-Dec-17  How investing in solar energy can create a bri...
17796  17-Dec-17     Poundland suppliers hit by insurance downgrade
17797  17-Dec-17  Cryptocurrencies: City watchdog to investigate...
17798  17-Dec-17  Unilever sells household name spreads to KKR f...
17799  17-Dec-17  The Guardian view on Ryanair’s model: a union-...

[17800 rows x 2 columns]

In [13]:
df3 = pd.read_csv(csv3)
df3

,Headlines,Time,Description
0,TikTok considers London and other locations fo...,Jul 18 2020,TikTok has been in discussions with the UK gov...
1,Disney cuts ad spending on Facebook amid growi...,Jul 18 2020,Walt Disney has become the latest company to ...
2,Trail of missing Wirecard executive leads to B...,Jul 18 2020,Former Wirecard chief operating officer Jan M...
3,Twitter says attackers downloaded data from up...,Jul 18 2020,Twitter Inc said on Saturday that hackers were...
4,U.S. Republicans seek liability protections as...,Jul 17 2020,A battle in the U.S. Congress over a new coron...
...,...,...,...
32765,Malaysia says never hired British data firm at...,Mar 20 2018,The Malaysian government and the ruling party ...
32766,Prosecutors search Volkswagen headquarters in ...,Mar 20 2018,German prosecutors said on Tuesday they had se...
32767,McDonald's sets greenhouse gas reduction targets,Mar 20 2018,McDonald's Corp on Tuesday announced an approv...
32768,Pratt & Whitney to deliver spare A320neo engin...,Mar 20 2018,Pratt & Whitney will soon begin deliveries of ...
32769,UK will always consider ways to improve data l...,Mar 20 2018,Britain will consider any suggestions to give ...

### clean df1

In [14]:
df1 = df1.drop(columns=['Description']).dropna()
df1

,Headlines,Time
0,Jim Cramer: A better way to invest in the Covi...,"7:51 PM ET Fri, 17 July 2020"
1,Cramer's lightning round: I would own Teradyne,"7:33 PM ET Fri, 17 July 2020"
3,"Cramer's week ahead: Big week for earnings, ev...","7:25 PM ET Fri, 17 July 2020"
4,IQ Capital CEO Keith Bliss says tech and healt...,"4:24 PM ET Fri, 17 July 2020"
5,Wall Street delivered the 'kind of pullback I'...,"7:36 PM ET Thu, 16 July 2020"
...,...,...
3075,Markets lack Christmas cheer,"10:15 AM ET Tue, 26 Dec 2017"
3076,Cramer Remix: The biggest mistake you can make...,"11:12 AM ET Thu, 20 Sept 2018"
3077,Cramer says owning too many stocks and too lit...,"7:07 PM ET Fri, 22 Dec 2017"
3078,Cramer: I helped investors through the 2010 fl...,"7:07 PM ET Fri, 22 Dec 2017"
3079,Cramer: Never buy a stock all at once — you'll...,"6:52 PM ET Fri, 22 Dec 2017"

In [15]:
def convert_time_format(time_str):
    cleaned_time = " ".join(time_str.split())
    dt = parser.parse(cleaned_time)
    et = timezone("US/Eastern")
    return dt.replace(tzinfo=et) 

df1['Time'] = df1['Time'].apply(convert_time_format)
df1

/home/kuba/miniconda3/envs/nlp/lib/python3.11/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname ET identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "

,Headlines,Time
0,Jim Cramer: A better way to invest in the Covi...,2020-07-17 20:47:00-04:00
1,Cramer's lightning round: I would own Teradyne,2020-07-17 20:29:00-04:00
3,"Cramer's week ahead: Big week for earnings, ev...",2020-07-17 20:21:00-04:00
4,IQ Capital CEO Keith Bliss says tech and healt...,2020-07-17 17:20:00-04:00
5,Wall Street delivered the 'kind of pullback I'...,2020-07-16 20:32:00-04:00
...,...,...
3075,Markets lack Christmas cheer,2017-12-26 10:11:00-05:00
3076,Cramer Remix: The biggest mistake you can make...,2018-09-20 12:08:00-04:00
3077,Cramer says owning too many stocks and too lit...,2017-12-22 19:03:00-05:00
3078,Cramer: I helped investors through the 2010 fl...,2017-12-22 19:03:00-05:00
3079,Cramer: Never buy a stock all at once — you'll...,2017-12-22 18:48:00-05:00

### clean df2

In [16]:
df2 = df2.dropna()
df2['Time'] = df2['Time'].apply(convert_time_format)
df2

,Time,Headlines
0,2020-07-18 00:56:00-04:00,Johnson is asking Santa for a Christmas recovery
1,2020-07-18 00:56:00-04:00,‘I now fear the worst’: four grim tales of wor...
2,2020-07-18 00:56:00-04:00,Five key areas Sunak must tackle to serve up e...
3,2020-07-18 00:56:00-04:00,Covid-19 leaves firms ‘fatally ill-prepared’ f...
4,2020-07-18 00:56:00-04:00,The Week in Patriarchy \n\n\n Bacardi's 'lad...
...,...,...
17795,2017-12-16 23:56:00-05:00,How investing in solar energy can create a bri...
17796,2017-12-16 23:56:00-05:00,Poundland suppliers hit by insurance downgrade
17797,2017-12-16 23:56:00-05:00,Cryptocurrencies: City watchdog to investigate...
17798,2017-12-16 23:56:00-05:00,Unilever sells household name spreads to KKR f...
17799,2017-12-16 23:56:00-05:00,The Guardian view on Ryanair’s model: a union-...

### cleand df3

In [17]:
df3 = df3.drop(columns=['Description']).dropna()
df3['Time'] = df3['Time'].apply(convert_time_format)
df3

,Headlines,Time
0,TikTok considers London and other locations fo...,2020-07-18 00:56:00-04:00
1,Disney cuts ad spending on Facebook amid growi...,2020-07-18 00:56:00-04:00
2,Trail of missing Wirecard executive leads to B...,2020-07-18 00:56:00-04:00
3,Twitter says attackers downloaded data from up...,2020-07-18 00:56:00-04:00
4,U.S. Republicans seek liability protections as...,2020-07-17 00:56:00-04:00
...,...,...
32765,Malaysia says never hired British data firm at...,2018-03-20 00:56:00-04:00
32766,Prosecutors search Volkswagen headquarters in ...,2018-03-20 00:56:00-04:00
32767,McDonald's sets greenhouse gas reduction targets,2018-03-20 00:56:00-04:00
32768,Pratt & Whitney to deliver spare A320neo engin...,2018-03-20 00:56:00-04:00
32769,UK will always consider ways to improve data l...,2018-03-20 00:56:00-04:00

In [18]:
df = pd.concat([df1, df2, df3])
df = df.sort_values(by="Time").reset_index(drop=True)
df

,Headlines,Time
0,The Guardian view on Ryanair’s model: a union-...,2017-12-16 23:56:00-05:00
1,Peter Preston on press and broadcasting \n\n\...,2017-12-16 23:56:00-05:00
2,Why business could prosper under a Corbyn gove...,2017-12-16 23:56:00-05:00
3,Youngest staff to be given UK workplace pensio...,2017-12-16 23:56:00-05:00
4,Grogonomics \n\n\n This year has been about ...,2017-12-16 23:56:00-05:00
...,...,...
53365,"Pretty, peppery, perfect for summer: heatwave ...",2025-07-18 00:56:00-04:00
53366,Oxford buses turn to Uber-style apps in on-dem...,2025-07-18 00:56:00-04:00
53367,The shifting patterns of English \n\n\n May ...,2025-07-18 00:56:00-04:00
53368,Pubs and retailers hope for end to CO2 shortag...,2025-07-18 00:56:00-04:00
53369,Dealers shift down a gear as Brexit takes the ...,2025-07-18 00:56:00-04:00

In [19]:
df['Headlines'] = df['Headlines'].apply(lambda s : s.replace('\n\n\n', ''))
df

,Headlines,Time
0,The Guardian view on Ryanair’s model: a union-...,2017-12-16 23:56:00-05:00
1,Peter Preston on press and broadcasting Pau...,2017-12-16 23:56:00-05:00
2,Why business could prosper under a Corbyn gove...,2017-12-16 23:56:00-05:00
3,Youngest staff to be given UK workplace pensio...,2017-12-16 23:56:00-05:00
4,Grogonomics This year has been about compan...,2017-12-16 23:56:00-05:00
...,...,...
53365,"Pretty, peppery, perfect for summer: heatwave ...",2025-07-18 00:56:00-04:00
53366,Oxford buses turn to Uber-style apps in on-dem...,2025-07-18 00:56:00-04:00
53367,The shifting patterns of English May I have...,2025-07-18 00:56:00-04:00
53368,Pubs and retailers hope for end to CO2 shortag...,2025-07-18 00:56:00-04:00
53369,Dealers shift down a gear as Brexit takes the ...,2025-07-18 00:56:00-04:00

In [20]:
df.to_csv('../../data/news.csv', index=False)